export const FETCH_PRECINCT = 'FETCH_PRECINCT';
export const MERGE_PRECINCT = 'MERGE_PRECINCT';
export const UPDATE_PRECINCT = 'UPDATE_PRECINCT';
export const CREATE_GHOST_PRECINCT = 'CREATE_GHOST_PRECINCT';
export const FETCH_STATE = 'FETCH_STATE';
export const SELECT_STATE = 'SELECT_STATE';
